(() => {
'use strict';
const $=id=>document.getElementById(id), COLORS=window.PINDOU_MARD_COLORS||[];
if(!COLORS.length)return;
const MARD=new Map(COLORS.map(x=>[x[0],x])), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const mean=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0, median=a=>{if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:(b[m-1]+b[m])/2};
const lum=x=>.2126*x[0]+.7152*x[1]+.0722*x[2], sat=x=>{const hi=Math.max(...x),lo=Math.min(...x);return hi?(hi-lo)/hi:0}, hex=x=>'#'+x.map(v=>clamp(Math.round(v),0,255).toString(16).padStart(2,'0')).join('');
function norm(raw){let s=String(raw||'').toUpperCase().replace(/[^A-Z0-9]/g,'');if(MARD.has(s))return s;const m=s.match(/^([A-Z]{1,2})([0-9OILSZGB]{1,3})$/);if(!m)return'';s=m[1]+m[2].replace(/O/g,'0').replace(/[IL]/g,'1').replace(/Z/g,'2').replace(/S/g,'5').replace(/G/g,'6').replace(/B/g,'8');return MARD.has(s)?s:''}
function srgb(v){v/=255;return v<=.04045?v/12.92:Math.pow((v+.055)/1.055,2.4)}
function lab(a){const r=srgb(a[0]),g=srgb(a[1]),b=srgb(a[2]),x=(.4124*r+.3576*g+.1805*b)/.95047,y=.2126*r+.7152*g+.0722*b,z=(.0193*r+.1192*g+.9505*b)/1.08883,f=t=>t>.008856?Math.cbrt(t):7.787*t+16/116,fx=f(x),fy=f(y),fz=f(z);return[116*fy-16,500*(fx-fy),200*(fy-fz)]}
function de(a,b){const A=lab(a),B=lab(b);return Math.hypot(A[0]-B[0],A[1]-B[1],A[2]-B[2])}
function notice(t,k='ok'){const e=$('detectNotice');if(e){e.textContent=t;e.className=`notice ${k}`;e.classList.remove('hidden')}}
function rect(){const c=$('sourceCanvas'),o=$('cropOverlay');if(!c?.width||!o)return null;let x=parseFloat(o.style.left),y=parseFloat(o.style.top),w=parseFloat(o.style.width),h=parseFloat(o.style.height);if(!Number.isFinite(x)||!Number.isFinite(y)||!Number.isFinite(w)||!Number.isFinite(h)||w<2||h<2){x=0;y=0;w=c.width;h=c.height}return{x:clamp(x,0,c.width-1),y:clamp(y,0,c.height-1),w:clamp(w,1,c.width-x),h:clamp(h,1,c.height-y)}}
function crop(src,r){const c=document.createElement('canvas');c.width=Math.round(r.w);c.height=Math.round(r.h);c.getContext('2d',{willReadFrequently:true}).drawImage(src,r.x,r.y,r.w,r.h,0,0,c.width,c.height);return c}
function sample(data,W,H,x,y,w,h){const x0=Math.max(0,Math.floor(x+w*.17)),x1=Math.min(W,Math.ceil(x+w*.83)),y0=Math.max(0,Math.floor(y+h*.17)),y1=Math.min(H,Math.ceil(y+h*.83)),step=Math.max(1,Math.floor(Math.min(w,h)/18)),bins=new Map(),px=[];for(let yy=y0;yy<y1;yy+=step)for(let xx=x0;xx<x1;xx+=step){const i=(yy*W+xx)*4,p=[data[i],data[i+1],data[i+2]],k=`${Math.round(p[0]/8)*8},${Math.round(p[1]/8)*8},${Math.round(p[2]/8)*8}`;px.push(p);bins.set(k,(bins.get(k)||0)+1)}let k='255,255,255',bn=-1;for(const[a,n]of bins)if(n>bn){bn=n;k=a}const b=k.split(',').map(Number),q=px.filter(p=>Math.hypot(p[0]-b[0],p[1]-b[1],p[2]-b[2])<27),rgb=[0,1,2].map(j=>Math.round(mean((q.length?q:px).map(p=>p[j]))));let ink=0;for(const p of px)if(Math.hypot(p[0]-rgb[0],p[1]-rgb[1],p[2]-rgb[2])>36&&Math.abs(lum(p)-lum(rgb))>20)ink++;return{rgb,ink:ink/Math.max(1,px.length)}}
function build(c,S){const X=c.getContext('2d',{willReadFrequently:true}),W=c.width,H=c.height,d=X.getImageData(0,0,W,H).data,a=[];for(let r=0;r<S.rows;r++)for(let col=0;col<S.cols;col++){const x=col*W/S.cols,y=r*H/S.rows,w=W/S.cols,h=H/S.rows,z=sample(d,W,H,x,y,w,h),orig=S.cells[r*S.cols+col],occ=!!(orig?.occupied||orig?.code||sat(z.rgb)>.045||lum(z.rgb)<235||z.ink>.018);a.push({r,col,x,y,w,h,...z,orig,occ,cluster:-1})}return a}
function clusters(a){const qs=[];for(const s of a){if(!s.occ)continue;let bi=-1,bd=1e9;for(let i=0;i<qs.length;i++){const d=de(s.rgb,qs[i].rgb);if(d<bd){bd=d;bi=i}}if(bi>=0&&bd<2.7){const q=qs[bi],n=q.a.length;q.a.push(s);q.rgb=q.rgb.map((v,j)=>(v*n+s.rgb[j])/(n+1));s.cluster=bi}else{s.cluster=qs.length;qs.push({rgb:[...s.rgb],a:[s],current:new Map(),pick:'',conf:'low'})}}for(const q of qs)for(const s of q.a){const k=norm(s.orig?.code);if(k)q.current.set(k,(q.current.get(k)||0)+1)}return qs}
function ref(code,off=[0,0,0]){const e=MARD.get(code);return[e[1]+off[0],e[2]+off[1],e[3]+off[2]].map(v=>clamp(v,0,255))}
function current(q){return[...q.current].sort((a,b)=>b[1]-a[1])[0]?.[0]||''}
function calibrate(qs){const p=[];for(const q of qs){const k=current(q);if(!k)continue;const r=ref(k),d=de(q.rgb,r);if(d<12)p.push({r,o:q.rgb})}return p.length?[0,1,2].map(ch=>clamp(median(p.map(x=>x.o[ch]-x.r[ch])),-40,40)):[0,0,0]}
function nearest(rgb,off){let a=[];for(const e of COLORS)a.push({k:e[0],d:de(rgb,ref(e[0],off))});a.sort((x,y)=>x.d-y.d);return a.slice(0,5)}
function tile(c,s){const sw=Math.max(2,Math.round(s.w*.84)),sh=Math.max(2,Math.round(s.h*.84)),sx=Math.round(s.x+s.w*.08),sy=Math.round(s.y+s.h*.08),m=document.createElement('canvas');m.width=sw;m.height=sh;const X=m.getContext('2d',{willReadFrequently:true});X.drawImage(c,sx,sy,sw,sh,0,0,sw,sh);const im=X.getImageData(0,0,sw,sh),d=im.data,B=s.rgb,L=lum(B);for(let i=0;i<d.length;i+=4){const p=[d[i],d[i+1],d[i+2]],ink=Math.hypot(p[0]-B[0],p[1]-B[1],p[2]-B[2])>32&&Math.abs(lum(p)-L)>16,v=ink?0:255;d[i]=d[i+1]=d[i+2]=v;d[i+3]=255}X.putImageData(im,0,0);const t=document.createElement('canvas');t.width=220;t.height=120;const T=t.getContext('2d');T.fillStyle='#fff';T.fillRect(0,0,220,120);T.imageSmoothingEnabled=false;const sc=Math.min(190/sw,88/sh),dw=Math.round(sw*sc),dh=Math.round(sh*sc);T.drawImage(m,0,0,sw,sh,(220-dw)/2,(120-dh)/2,dw,dh);return t}
async function resolve(worker,c,q,cands){const votes=new Map(), reps=[...q.a].sort((a,b)=>(b.orig?.direct?1:0)-(a.orig?.direct?1:0)).slice(0,3);await worker.setParameters({tessedit_pageseg_mode:'8',tessedit_char_whitelist:'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'});for(const s of reps){try{const z=await worker.recognize(tile(c,s)),k=norm(z.data?.text);if(k&&cands.some(x=>x.k===k))votes.set(k,(votes.get(k)||0)+1)}catch(_){}}return[...votes].sort((a,b)=>b[1]-a[1])[0]?.[0]||''}
async function refine(){const S=window.__pindouV6,src=$('sourceCanvas'),r=rect();if(!S?.active||!S.worker||!r)return;const c=crop(src,r),a=build(c,S),qs=clusters(a),off=calibrate(qs);notice(`V8 最终校色：检测到 ${qs.length} 个实际底色，正在纠正“颜色有但编号错”的格子…`);let changed=0,amb=0;for(let i=0;i<qs.length;i++){const q=qs[i],near=nearest(q.rgb,off),best=near[0],second=near[1],old=current(q),oldD=old?de(q.rgb,ref(old,off)):1e9;let k=best.k,conf='medium';if(old&&oldD<=best.d+2.3&&oldD<15){k=old;conf='high'}else if(best.d<9&&(second.d-best.d)>.7){conf='high'}else if((second.d-best.d)<1.6){amb++;const ocr=await resolve(S.worker,c,q,near);if(ocr){k=ocr;conf='high'}else conf='medium'}else if(best.d>18){conf='low'}q.pick=k;q.conf=conf;for(const s of q.a){if(s.orig.code!==k)changed++;s.orig.code=k;s.orig.rgb=[...s.rgb];s.orig.hex=hex(s.rgb);s.orig.v8Confidence=conf;s.orig.occupied=true}if(i%4===0)notice(`V8 最终校色… ${i+1}/${qs.length}`)}$('showAllBtn')?.click();const low=qs.filter(q=>q.conf==='low').length;notice(`V8 完成：${qs.length} 种实际底色；修正 ${changed} 格；其中 ${amb} 个近似色组额外逐格 OCR 复核；低置信 ${low} 组。现在不会再让橙色被标成浅黄、青色被标成其他系列。`,low<=1?'ok':'warn')}
let timer=null;const n=$('detectNotice');if(n){new MutationObserver(()=>{const t=n.textContent||'';if(!t.startsWith('V7 精校完成'))return;clearTimeout(timer);timer=setTimeout(()=>refine().catch(e=>notice(`V8 校色失败：${e.message||e}`,'warn')),80)}).observe(n,{childList:true,characterData:true,subtree:true})}
})();
