(() => {
'use strict';
const $=id=>document.getElementById(id);
const COLORS=window.PINDOU_MARD_COLORS||[];
if(!COLORS.length)return;
const MARD=new Map(COLORS.map(x=>[x[0],x]));
const VALID=new Set(MARD.keys());
const S={rows:0,cols:0,cells:[],done:new Set(),selectedCode:null,selectedCell:null,worker:null,busy:false,active:false};
window.__pindouV11=S;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const mean=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0;
const median=a=>{if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),m=b.length>>1;return b.length%2?b[m]:(b[m-1]+b[m])/2};
const lum=x=>.2126*x[0]+.7152*x[1]+.0722*x[2];
const sat=x=>{const hi=Math.max(...x),lo=Math.min(...x);return hi?(hi-lo)/hi:0};
const hex=x=>'#'+x.map(v=>clamp(Math.round(v),0,255).toString(16).padStart(2,'0')).join('');
function norm(raw){let s=String(raw||'').toUpperCase().replace(/[^A-Z0-9]/g,'');if(VALID.has(s))return s;const m=s.match(/^([A-Z]{1,2})([0-9OILSZGB]{1,3})$/);if(!m)return'';s=m[1]+m[2].replace(/O/g,'0').replace(/[IL]/g,'1').replace(/Z/g,'2').replace(/S/g,'5').replace(/G/g,'6').replace(/B/g,'8');return VALID.has(s)?s:''}
function srgb(v){v/=255;return v<=.04045?v/12.92:Math.pow((v+.055)/1.055,2.4)}
function lab(a){const r=srgb(a[0]),g=srgb(a[1]),b=srgb(a[2]),x=(.4124*r+.3576*g+.1805*b)/.95047,y=.2126*r+.7152*g+.0722*b,z=(.0193*r+.1192*g+.9505*b)/1.08883,f=t=>t>.008856?Math.cbrt(t):7.787*t+16/116,fx=f(x),fy=f(y),fz=f(z);return[116*fy-16,500*(fx-fy),200*(fy-fz)]}
function de(a,b){const A=lab(a),B=lab(b);return Math.hypot(A[0]-B[0],A[1]-B[1],A[2]-B[2])}
function notice(t,k='ok'){const e=$('detectNotice');if(e){e.textContent=t;e.className=`notice ${k}`;e.classList.remove('hidden')}}
function progress(t,p){const b=$('progressBox');if(!b)return;b.classList.remove('hidden');$('progressText').textContent=t;$('progressPct').textContent=`${Math.round(p)}%`;$('progressBar').style.width=`${clamp(p,0,100)}%`}
function hideProgress(){$('progressBox')?.classList.add('hidden')}
function toast(t){const e=$('toast');if(!e)return;e.textContent=t;e.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add('hidden'),1800)}
async function getWorker(){if(S.worker)return S.worker;if(!window.Tesseract)throw new Error('OCR 组件未加载，请联网刷新页面');S.worker=await Tesseract.createWorker('eng',1,{logger:m=>{if(m.status==='recognizing text'&&S.busy)progress('正在读取颜色编号…',25+(m.progress||0)*50)}});await S.worker.setParameters({tessedit_char_whitelist:'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789()[]',preserve_interword_spaces:'0'});return S.worker}
function cropRect(){const c=$('sourceCanvas'),o=$('cropOverlay');if(!c?.width)throw new Error('请先上传图纸');let x=parseFloat(o?.style.left),y=parseFloat(o?.style.top),w=parseFloat(o?.style.width),h=parseFloat(o?.style.height);if(!Number.isFinite(x)||!Number.isFinite(y)||!Number.isFinite(w)||!Number.isFinite(h)||w<2||h<2){x=0;y=0;w=c.width;h=c.height}x=clamp(x,0,c.width-1);y=clamp(y,0,c.height-1);w=clamp(w,1,c.width-x);h=clamp(h,1,c.height-y);return{x,y,w,h}}
function cropCanvas(src,r){const c=document.createElement('canvas');c.width=Math.max(1,Math.round(r.w));c.height=Math.max(1,Math.round(r.h));c.getContext('2d',{willReadFrequently:true}).drawImage(src,r.x,r.y,r.w,r.h,0,0,c.width,c.height);return c}
function dominant(data,W,H,x,y,w,h){const x0=Math.max(0,Math.floor(x+w*.16)),x1=Math.min(W,Math.ceil(x+w*.84)),y0=Math.max(0,Math.floor(y+h*.16)),y1=Math.min(H,Math.ceil(y+h*.84)),step=Math.max(1,Math.floor(Math.min(w,h)/18)),bins=new Map(),px=[];for(let yy=y0;yy<y1;yy+=step)for(let xx=x0;xx<x1;xx+=step){const i=(yy*W+xx)*4,p=[data[i],data[i+1],data[i+2]],k=`${Math.round(p[0]/7)*7},${Math.round(p[1]/7)*7},${Math.round(p[2]/7)*7}`;px.push(p);bins.set(k,(bins.get(k)||0)+1)}let key='255,255,255',bn=-1;for(const[k,n]of bins)if(n>bn){bn=n;key=k}const base=key.split(',').map(Number),near=px.filter(p=>Math.hypot(p[0]-base[0],p[1]-base[1],p[2]-base[2])<24),rgb=[0,1,2].map(j=>Math.round(mean((near.length?near:px).map(p=>p[j]))));let ink=0;for(const p of px){const d=Math.hypot(p[0]-rgb[0],p[1]-rgb[1],p[2]-rgb[2]),ld=Math.abs(lum(p)-lum(rgb));if(d>31&&ld>14)ink++}return{rgb,ink:ink/Math.max(1,px.length),support:bn/Math.max(1,px.length)}}
function buildCells(c,rows,cols){const X=c.getContext('2d',{willReadFrequently:true}),W=c.width,H=c.height,d=X.getImageData(0,0,W,H).data,out=[];for(let r=0;r<rows;r++)for(let col=0;col<cols;col++){const x=col*W/cols,y=r*H/rows,w=W/cols,h=H/rows,z=dominant(d,W,H,x,y,w,h),blank=sat(z.rgb)<.032&&lum(z.rgb)>230&&z.ink<.024;out.push({r,c:col,x,y,w,h,rgb:z.rgb,hex:hex(z.rgb),ink:z.ink,support:z.support,occupied:!blank,code:'',votes:new Map(),confidence:'none',cluster:-1})}return out}
function makeClusters(cells){const qs=[];for(const s of cells){if(!s.occupied)continue;let bi=-1,bd=1e9;for(let i=0;i<qs.length;i++){const d=de(s.rgb,qs[i].rgb);if(d<bd){bd=d;bi=i}}if(bi>=0&&bd<4.1){const q=qs[bi],n=q.cells.length;q.cells.push(s);q.rgb=q.rgb.map((v,j)=>(v*n+s.rgb[j])/(n+1));s.cluster=bi}else{s.cluster=qs.length;qs.push({rgb:[...s.rgb],cells:[s],votes:new Map(),code:'',confidence:'none'})}}return qs}
function region(src,x,y,w,h,max=2600){if(w<18||h<18)return null;const sc=Math.min(5,max/Math.max(w,h)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(w*sc));c.height=Math.max(1,Math.round(h*sc));c.getContext('2d',{willReadFrequently:true}).drawImage(src,x,y,w,h,0,0,c.width,c.height);return c}
function parseLegendText(text){const codes=new Set(),counts=new Map(),s=String(text||'').toUpperCase();for(const m of s.matchAll(/(?:ZG|[A-HMPRQTY])\s*[0-9OILSZGB]{1,2}/g)){const k=norm(m[0]);if(k)codes.add(k)}for(const m of s.replace(/\n/g,' ').matchAll(/((?:ZG|[A-HMPRQTY])\s*[0-9OILSZGB]{1,2})\s*[\(\[]?\s*(\d{1,3})\s*[\)\]]?/g)){const k=norm(m[1]),n=parseInt(m[2],10);if(k&&n>0&&n<1000){codes.add(k);counts.set(k,n)}}return{codes,counts}}
async function readLegend(w,src,r){const regs=[],bottom=src.height-r.y-r.h,right=src.width-r.x-r.w,top=r.y,left=r.x;if(bottom>22)regs.push(region(src,0,r.y+r.h,src.width,bottom));if(right>22)regs.push(region(src,r.x+r.w,0,right,src.height));if(top>22)regs.push(region(src,0,0,src.width,top));if(left>22)regs.push(region(src,0,0,left,src.height));const codes=new Set(),counts=new Map();for(const c of regs.filter(Boolean)){for(const psm of ['6','11']){try{await w.setParameters({tessedit_pageseg_mode:psm,tessedit_char_whitelist:'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789()[]'});const z=await w.recognize(c),p=parseLegendText(z.data?.text);for(const k of p.codes)codes.add(k);for(const[k,n]of p.counts)counts.set(k,n)}catch(_){}}}return{codes,counts}}
function tile(c,s,binary=true){const TW=144,TH=92,t=document.createElement('canvas');t.width=TW;t.height=TH;const T=t.getContext('2d',{willReadFrequently:true});T.fillStyle='#fff';T.fillRect(0,0,TW,TH);const sx=s.x+s.w*.07,sy=s.y+s.h*.07,sw=s.w*.86,sh=s.h*.86,raw=document.createElement('canvas');raw.width=Math.max(2,Math.round(sw));raw.height=Math.max(2,Math.round(sh));const R=raw.getContext('2d',{willReadFrequently:true});R.drawImage(c,sx,sy,sw,sh,0,0,raw.width,raw.height);if(binary){const im=R.getImageData(0,0,raw.width,raw.height),d=im.data,B=s.rgb,L=lum(B);for(let i=0;i<d.length;i+=4){const p=[d[i],d[i+1],d[i+2]],dist=Math.hypot(p[0]-B[0],p[1]-B[1],p[2]-B[2]),ld=Math.abs(lum(p)-L),isInk=dist>25&&(ld>8||dist>55),v=isInk?0:255;d[i]=d[i+1]=d[i+2]=v;d[i+3]=255}R.putImageData(im,0,0)}T.imageSmoothingEnabled=false;const sc=Math.min(126/raw.width,74/raw.height),dw=Math.max(1,Math.round(raw.width*sc)),dh=Math.max(1,Math.round(raw.height*sc));T.drawImage(raw,0,0,raw.width,raw.height,(TW-dw)/2,(TH-dh)/2,dw,dh);return t}
function representativeCells(q){const a=[...q.cells].sort((x,y)=>(y.ink-x.ink)|| (y.support-x.support));if(a.length<=4)return a;return[a[0],a[Math.floor(a.length*.25)],a[Math.floor(a.length*.55)],a[a.length-1]]}
function clusterSheet(c,qs,binary){const picks=[];qs.forEach((q,qi)=>representativeCells(q).forEach(s=>picks.push({q,qi,s})));const TW=144,TH=92,NC=6,sh=document.createElement('canvas');sh.width=NC*TW;sh.height=Math.max(TH,Math.ceil(picks.length/NC)*TH);const X=sh.getContext('2d');X.fillStyle='#fff';X.fillRect(0,0,sh.width,sh.height);picks.forEach((p,i)=>X.drawImage(tile(c,p.s,binary),(i%NC)*TW,Math.floor(i/NC)*TH));return{sh,picks,TW,TH,NC}}
async function ocrClusters(w,c,qs,legend){let hits=0;for(const binary of [true,false]){const{sh,picks,TW,TH,NC}=clusterSheet(c,qs,binary);for(const psm of ['6','11']){try{await w.setParameters({tessedit_pageseg_mode:psm,tessedit_char_whitelist:'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'});const z=await w.recognize(sh);for(const word of z.data?.words||[]){const k=norm(word.text);if(!k||!word.bbox)continue;const cx=(word.bbox.x0+word.bbox.x1)/2,cy=(word.bbox.y0+word.bbox.y1)/2,idx=Math.floor(cy/TH)*NC+Math.floor(cx/TW),p=picks[idx];if(!p)continue;const weight=legend.codes.has(k)?2:1;p.q.votes.set(k,(p.q.votes.get(k)||0)+weight);hits++}}catch(_){}}}return hits}
function cellSheet(c,cells,binary){const TW=144,TH=92,NC=6,sh=document.createElement('canvas');sh.width=NC*TW;sh.height=Math.max(TH,Math.ceil(cells.length/NC)*TH);const X=sh.getContext('2d');X.fillStyle='#fff';X.fillRect(0,0,sh.width,sh.height);cells.forEach((s,i)=>X.drawImage(tile(c,s,binary),(i%NC)*TW,Math.floor(i/NC)*TH));return{sh,TW,TH,NC}}
async function resolveAmbiguousCluster(w,c,q){const votesByCell=new Map();for(const binary of [true,false]){const{sh,TW,TH,NC}=cellSheet(c,q.cells,binary);for(const psm of ['6','11']){try{await w.setParameters({tessedit_pageseg_mode:psm,tessedit_char_whitelist:'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'});const z=await w.recognize(sh);for(const word of z.data?.words||[]){const k=norm(word.text);if(!k||!word.bbox)continue;const idx=Math.floor(((word.bbox.y0+word.bbox.y1)/2)/TH)*NC+Math.floor(((word.bbox.x0+word.bbox.x1)/2)/TW),s=q.cells[idx];if(!s)continue;if(!votesByCell.has(s))votesByCell.set(s,new Map());const m=votesByCell.get(s);m.set(k,(m.get(k)||0)+1)}}catch(_){}}}return votesByCell}
function topVotes(m){const a=[...m].sort((x,y)=>y[1]-x[1]);return{one:a[0]||['',0],two:a[1]||['',0']}}
function official(k,off=[0,0,0]){const e=MARD.get(k);return[e[1]+off[0],e[2]+off[1],e[3]+off[2]].map(v=>clamp(v,0,255))}
function calibrate(qs){const dif=[[],[],[]];for(const q of qs){if(!q.code)continue;const e=MARD.get(q.code);if(!e)continue;for(let i=0;i<3;i++)dif[i].push(q.rgb[i]-e[i+1])}return dif.map(a=>clamp(median(a),-50,50))}
function nearestCodes(rgb,off,n=4){const a=[];for(const e of COLORS)a.push({k:e[0],d:de(rgb,official(e[0],off))});a.sort((x,y)=>x.d-y.d);return a.slice(0,n)}
async function assignClusters(w,c,qs,legend){let ambiguous=0,splitCells=0;for(const q of qs){const{one,two}=topVotes(q.votes);if(one[0]&&one[1]>=2&&(one[1]>=two[1]+2||one[1]>=4)){q.code=one[0];q.confidence='ocr-cluster'}else if(one[0]&&two[0]&&two[1]>=2&&two[1]>=one[1]*.45){ambiguous++;const per=await resolveAmbiguousCluster(w,c,q);const direct=[];for(const[s,m]of per){const t=topVotes(m);if(t.one[0]&&t.one[1]>=2&&t.one[1]>=t.two[1]+1){s.code=t.one[0];s.confidence='ocr-cell';direct.push(s);splitCells++}}const freq=new Map();for(const s of direct)freq.set(s.code,(freq.get(s.code)||0)+1);if(freq.size===1){q.code=[...freq.keys()][0];q.confidence='ocr-cell-majority'}}}
  const off=calibrate(qs),known=new Set([...legend.codes,...qs.filter(q=>q.code).map(q=>q.code)]);
  for(const q of qs){if(q.code)continue;const near=nearestCodes(q.rgb,off,5);let pick=near[0];for(const x of near){if(known.has(x.k)&&x.d<=pick.d+3.5){pick=x;break}}if(pick&&pick.d<18){q.code=pick.k;q.confidence=known.has(pick.k)?'color-known':'color-fallback';known.add(pick.k)}}
  for(const q of qs){for(const s of q.cells){if(s.code){s.hex=hex(s.rgb);continue}if(q.code){s.code=q.code;s.confidence=q.confidence;s.hex=hex(s.rgb)}}}
  return{ambiguous,splitCells,off}}
function normalizeSameCode(qs){const by=new Map();for(const q of qs){if(!q.code)continue;if(!by.has(q.code))by.set(q.code,[]);by.get(q.code).push(q)}for(const arr of by.values()){if(arr.length<2)continue;const all=arr.flatMap(q=>q.cells),rgb=[0,1,2].map(i=>Math.round(median(all.map(s=>s.rgb[i]))));for(const s of all){s.rgb=[...rgb];s.hex=hex(rgb)}}}
function groups(){const m=new Map();for(const s of S.cells){if(!s.code)continue;if(!m.has(s.code))m.set(s.code,{code:s.code,count:0,rgb:s.rgb});const g=m.get(s.code);g.count++;}return[...m.values()].sort((a,b)=>b.count-a.count||a.code.localeCompare(b.code))}
function draw(){const cv=$('gridCanvas'),size=+$('zoomRange').value||34;$('zoomValue').textContent=String(size);cv.width=S.cols*size+1;cv.height=S.rows*size+1;const X=cv.getContext('2d');X.font=`${Math.max(7,Math.floor(size*.28))}px -apple-system,BlinkMacSystemFont,sans-serif`;X.textAlign='center';X.textBaseline='middle';for(const s of S.cells){const x=s.c*size,y=s.r*size,vis=!S.selectedCode||s.code===S.selectedCode;X.globalAlpha=s.code?(vis?1:.07):1;X.fillStyle=s.code?s.hex:'#fff';X.fillRect(x,y,size,size);if(s.code&&vis){X.fillStyle=lum(s.rgb)<135?'#fff':'#222';X.fillText(s.code,x+size/2,y+size/2)}if(S.done.has(`${s.r},${s.c}`)&&vis){X.strokeStyle='#111';X.lineWidth=2;X.beginPath();X.moveTo(x+size*.22,y+size*.52);X.lineTo(x+size*.42,y+size*.7);X.lineTo(x+size*.78,y+size*.26);X.stroke()}X.globalAlpha=1;X.strokeStyle='rgba(0,0,0,.16)';X.lineWidth=1;X.strokeRect(x+.5,y+.5,size,size)}X.strokeStyle='#111';X.lineWidth=2.5;for(let x=5;x<S.cols;x+=5){X.beginPath();X.moveTo(x*size+.5,0);X.lineTo(x*size+.5,cv.height);X.stroke()}for(let y=5;y<S.rows;y+=5){X.beginPath();X.moveTo(0,y*size+.5);X.lineTo(cv.width,y*size+.5);X.stroke()}}
function render(){const gs=groups(),recognized=S.cells.filter(s=>s.code).length;$('stats').innerHTML=`<div class="stat"><span>网格</span><b>${S.cols}×${S.rows}</b></div><div class="stat"><span>颜色</span><b>${gs.length}</b></div><div class="stat"><span>已识别</span><b>${recognized}</b></div><div class="stat"><span>已完成</span><b>${S.done.size}</b></div>`;const p=$('palette');p.innerHTML='';for(const g of gs){const b=document.createElement('button');b.type='button';b.className='chip'+(S.selectedCode===g.code?' active':'');b.dataset.v11code=g.code;b.innerHTML=`<div class="chip-color" style="background:${hex(g.rgb)}"></div><strong>${g.code}</strong><span>${g.count} 颗</span>`;p.appendChild(b)}$('activeCode').textContent=S.selectedCode||'全部';draw()}
function showCell(s){S.selectedCell=s;const e=$('currentCell');e.classList.remove('hidden');e.innerHTML=`<b>${s.code||'未识别'}</b> · 总第 ${s.r+1} 行 / 第 ${s.c+1} 列<br>5×5 模块：第 ${Math.floor(s.r/5)+1} 行模块 × 第 ${Math.floor(s.c/5)+1} 列模块；模块内第 ${s.r%5+1} 行 / 第 ${s.c%5+1} 列`;$('editCodeInput').value=s.code||''}
async function recognize(){const src=$('sourceCanvas');let cols=parseInt($('colsInput').value,10),rows=parseInt($('rowsInput').value,10);if(!src?.width)throw new Error('请先上传图纸');if(!cols||!rows||cols<1||rows<1||cols>160||rows>160)throw new Error('请先填写正确的列数和行数');if(rows*cols>12000)throw new Error('网格超过 12000 格，请分区识别');S.busy=true;$('recognizeBtn').disabled=true;try{progress('固定你填写的行列数，逐格采样底色…',5);const r=cropRect(),c=cropCanvas(src,r),cells=buildCells(c,rows,cols),qs=makeClusters(cells),w=await getWorker();progress('读取图纸自带色卡（只做提示，不再当白名单）…',15);const legend=await readLegend(w,src,r);progress(`检测到 ${qs.length} 个实际底色组，正在放大代表格 OCR…`,28);const hits=await ocrClusters(w,c,qs,legend);progress('合并同色格并复核近似色…',78);const info=await assignClusters(w,c,qs,legend);normalizeSameCode(qs);S.rows=rows;S.cols=cols;S.cells=cells;S.done.clear();S.selectedCode=null;S.selectedCell=null;S.active=true;render();$('workSection').classList.remove('hidden');const rec=cells.filter(s=>s.code).length,occ=cells.filter(s=>s.occupied).length,gs=groups();hideProgress();notice(`V11：实际底色 ${qs.length} 组；色卡读到 ${legend.codes.size} 种（仅加权，不限制）；代表格 OCR 命中 ${hits} 次；近似色复核 ${info.ambiguous} 组。最终 ${gs.length} 种颜色，识别 ${rec}/${occ} 个有内容格。`,gs.length>=Math.max(2,legend.codes.size*.7)?'ok':'warn');$('workSection').scrollIntoView({behavior:'smooth',block:'start'})}finally{S.busy=false;$('recognizeBtn').disabled=false}}

document.addEventListener('click',e=>{const b=e.target.closest?.('#recognizeBtn');if(!b)return;e.preventDefault();e.stopImmediatePropagation();recognize().catch(err=>{hideProgress();S.busy=false;$('recognizeBtn').disabled=false;notice(`识别失败：${err.message||err}`,'warn')})},true);
document.addEventListener('click',e=>{const b=e.target.closest?.('[data-v11code]');if(b){S.selectedCode=S.selectedCode===b.dataset.v11code?null:b.dataset.v11code;render();return}if(e.target.closest?.('#showAllBtn')){S.selectedCode=null;render();return}if(e.target.closest?.('#nextBtn')){const list=S.cells.filter(s=>s.code&&(!S.selectedCode||s.code===S.selectedCode)&&!S.done.has(`${s.r},${s.c}`));if(!list.length){toast('这一色已经全部完成');return}showCell(list[0]);const size=+$('zoomRange').value||34;$('gridScroller').scrollTo({left:Math.max(0,list[0].c*size-120),top:Math.max(0,list[0].r*size-150),behavior:'smooth'});return}if(e.target.closest?.('#saveCodeBtn')){if(!S.selectedCell)return toast('先点一个格子');const k=norm($('editCodeInput').value);if(!k)return toast('请输入有效 MARD 色号');S.selectedCell.code=k;const m=MARD.get(k);S.selectedCell.rgb=[m[1],m[2],m[3]];S.selectedCell.hex=hex(S.selectedCell.rgb);render();showCell(S.selectedCell);toast('已修改');return}},true);
$('gridCanvas')?.addEventListener('click',e=>{if(!S.active)return;const cv=$('gridCanvas'),r=cv.getBoundingClientRect(),size=+$('zoomRange').value||34,c=Math.floor((e.clientX-r.left)*cv.width/r.width/size),rr=Math.floor((e.clientY-r.top)*cv.height/r.height/size);if(c<0||rr<0||c>=S.cols||rr>=S.rows)return;const s=S.cells[rr*S.cols+c];showCell(s);if(s.code){const k=`${rr},${c}`;S.done.has(k)?S.done.delete(k):S.done.add(k);render()}},true);
$('zoomRange')?.addEventListener('input',()=>{if(S.active)draw()});

// Mobile crop fine tuning: drag the existing box, drag 8 handles, or nudge by 1px.
const style=document.createElement('style');style.textContent=`.v11-crop-active{pointer-events:auto!important;touch-action:none}.v11-h{position:absolute;width:22px;height:22px;margin:-11px;border-radius:50%;background:#fff;border:3px solid #ff6f4d;box-shadow:0 2px 7px #0003;z-index:20;touch-action:none}.v11-nw{left:0;top:0}.v11-n{left:50%;top:0}.v11-ne{left:100%;top:0}.v11-e{left:100%;top:50%}.v11-se{left:100%;top:100%}.v11-s{left:50%;top:100%}.v11-sw{left:0;top:100%}.v11-w{left:0;top:50%}.v11-tools{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-top:8px}.v11-tools button{min-height:36px;padding:4px 6px;border-radius:10px;background:#fff7f1;border:1px solid #ead9cc;font-size:12px;font-weight:700}`;document.head.appendChild(style);
const ov=$('cropOverlay'),vp=$('sourceViewport'),cv=$('sourceCanvas');let drag=null,tools=null;
function orect(){return{x:parseFloat(ov.style.left)||0,y:parseFloat(ov.style.top)||0,w:parseFloat(ov.style.width)||cv.width,h:parseFloat(ov.style.height)||cv.height}}
function setRect(r){const W=cv.width,H=cv.height,m=8;r.x=clamp(r.x,0,W-m);r.y=clamp(r.y,0,H-m);r.w=clamp(r.w,m,W-r.x);r.h=clamp(r.h,m,H-r.y);ov.style.left=r.x+'px';ov.style.top=r.y+'px';ov.style.width=r.w+'px';ov.style.height=r.h+'px';const ci=$('cropInfo');if(ci)ci.textContent=`${Math.round(r.w)} × ${Math.round(r.h)} px`}
function ipt(e){const r=cv.getBoundingClientRect();return{x:(e.clientX-r.left)*cv.width/r.width,y:(e.clientY-r.top)*cv.height/r.height}}
function cropMode(){return vp?.classList.contains('mode-crop')}
function installHandles(){if(!ov||ov.querySelector('.v11-h'))return;for(const[k,cls]of [['nw','v11-nw'],['n','v11-n'],['ne','v11-ne'],['e','v11-e'],['se','v11-se'],['s','v11-s'],['sw','v11-sw'],['w','v11-w']]){const h=document.createElement('i');h.className=`v11-h ${cls}`;h.dataset.handle=k;ov.appendChild(h)}tools=document.createElement('div');tools.className='v11-tools';[['←1px','l'],['→1px','r'],['↑1px','u'],['↓1px','d'],['宽−','wm'],['宽＋','wp'],['高−','hm'],['高＋','hp']].forEach(([t,k])=>{const b=document.createElement('button');b.type='button';b.textContent=t;b.dataset.nudge=k;tools.appendChild(b)});($('sourceZoomValue')?.parentElement||vp).insertAdjacentElement('afterend',tools)}
function refreshCropUI(){if(!ov||!cv)return;installHandles();const r=orect(),full=Math.abs(r.x)<2&&Math.abs(r.y)<2&&Math.abs(r.w-cv.width)<3&&Math.abs(r.h-cv.height)<3;ov.classList.toggle('v11-crop-active',cropMode()&&!full);ov.querySelectorAll('.v11-h').forEach(h=>h.style.display=cropMode()&&!full?'block':'none');if(tools)tools.style.display=cropMode()?'grid':'none'}
if(ov&&vp&&cv){const mo=new MutationObserver(refreshCropUI);mo.observe(ov,{attributes:true,attributeFilter:['style','class']});vp.addEventListener('pointerdown',e=>{if(!cropMode()||!ov.classList.contains('v11-crop-active'))return;const h=e.target.closest?.('.v11-h');if(e.target!==ov&&!h)return;e.preventDefault();e.stopImmediatePropagation();const p=ipt(e),r=orect();drag={id:e.pointerId,p,r,h:h?.dataset.handle||'move'};vp.setPointerCapture?.(e.pointerId)},true);vp.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;e.preventDefault();e.stopImmediatePropagation();const p=ipt(e),dx=p.x-drag.p.x,dy=p.y-drag.p.y,r={...drag.r},h=drag.h;if(h==='move'){r.x+=dx;r.y+=dy}else{if(h.includes('w')){r.x+=dx;r.w-=dx}if(h.includes('e'))r.w+=dx;if(h.includes('n')){r.y+=dy;r.h-=dy}if(h.includes('s'))r.h+=dy}setRect(r)},true);const end=e=>{if(drag&&e.pointerId===drag.id){drag=null;refreshCropUI()}};vp.addEventListener('pointerup',end,true);vp.addEventListener('pointercancel',end,true);document.addEventListener('click',e=>{const b=e.target.closest?.('[data-nudge]');if(!b||!ov)return;const r=orect();switch(b.dataset.nudge){case'l':r.x--;break;case'r':r.x++;break;case'u':r.y--;break;case'd':r.y++;break;case'wm':r.w--;break;case'wp':r.w++;break;case'hm':r.h--;break;case'hp':r.h++;break}setRect(r)},true);document.addEventListener('click',()=>setTimeout(refreshCropUI,0));setTimeout(refreshCropUI,300)}
})();
