(() => {
'use strict';
const $=id=>document.getElementById(id), COLORS=window.PINDOU_MARD_COLORS||[];
if(!COLORS.length)return;
const MARD=new Map(COLORS.map(x=>[x[0],x])), VALID=new Set(MARD.keys());
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), mean=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0, median=a=>{if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),m=b.length>>1;return b.length%2?b[m]:(b[m-1]+b[m])/2};
const lum=x=>.2126*x[0]+.7152*x[1]+.0722*x[2], sat=x=>{const hi=Math.max(...x),lo=Math.min(...x);return hi?(hi-lo)/hi:0}, hex=x=>'#'+x.map(v=>clamp(Math.round(v),0,255).toString(16).padStart(2,'0')).join('');
function norm(raw){let s=String(raw||'').toUpperCase().replace(/[^A-Z0-9]/g,'');if(VALID.has(s))return s;const m=s.match(/^([A-Z]{1,2})([0-9OILSZGB]{1,3})$/);if(!m)return'';s=m[1]+m[2].replace(/O/g,'0').replace(/[IL]/g,'1').replace(/Z/g,'2').replace(/S/g,'5').replace(/G/g,'6').replace(/B/g,'8');return VALID.has(s)?s:''}
function srgb(v){v/=255;return v<=.04045?v/12.92:Math.pow((v+.055)/1.055,2.4)}
function lab(a){const r=srgb(a[0]),g=srgb(a[1]),b=srgb(a[2]),x=(.4124*r+.3576*g+.1805*b)/.95047,y=.2126*r+.7152*g+.0722*b,z=(.0193*r+.1192*g+.9505*b)/1.08883,f=t=>t>.008856?Math.cbrt(t):7.787*t+16/116,fx=f(x),fy=f(y),fz=f(z);return[116*fy-16,500*(fx-fy),200*(fy-fz)]}
function de(a,b){const A=lab(a),B=lab(b);return Math.hypot(A[0]-B[0],A[1]-B[1],A[2]-B[2])}
function notice(t,k='ok'){const e=$('detectNotice');if(e){e.textContent=t;e.className=`notice ${k}`;e.classList.remove('hidden')}}
function rect(){const c=$('sourceCanvas'),o=$('cropOverlay');if(!c?.width||!o)return null;let x=parseFloat(o.style.left),y=parseFloat(o.style.top),w=parseFloat(o.style.width),h=parseFloat(o.style.height);if(!Number.isFinite(x)||!Number.isFinite(y)||!Number.isFinite(w)||!Number.isFinite(h)||w<2||h<2){x=0;y=0;w=c.width;h=c.height}return{x:clamp(x,0,c.width-1),y:clamp(y,0,c.height-1),w:clamp(w,1,c.width-x),h:clamp(h,1,c.height-y)}}
function crop(src,r){const c=document.createElement('canvas');c.width=Math.max(1,Math.round(r.w));c.height=Math.max(1,Math.round(r.h));c.getContext('2d',{willReadFrequently:true}).drawImage(src,r.x,r.y,r.w,r.h,0,0,c.width,c.height);return c}
function dominant(data,W,H,x,y,w,h){const x0=Math.max(0,Math.floor(x+w*.18)),x1=Math.min(W,Math.ceil(x+w*.82)),y0=Math.max(0,Math.floor(y+h*.18)),y1=Math.min(H,Math.ceil(y+h*.82)),step=Math.max(1,Math.floor(Math.min(w,h)/18)),bins=new Map(),px=[];for(let yy=y0;yy<y1;yy+=step)for(let xx=x0;xx<x1;xx+=step){const i=(yy*W+xx)*4,p=[data[i],data[i+1],data[i+2]],k=`${Math.round(p[0]/7)*7},${Math.round(p[1]/7)*7},${Math.round(p[2]/7)*7}`;px.push(p);bins.set(k,(bins.get(k)||0)+1)}let key='255,255,255',bn=-1;for(const[k,n]of bins)if(n>bn){bn=n;key=k}const base=key.split(',').map(Number),near=px.filter(p=>Math.hypot(p[0]-base[0],p[1]-base[1],p[2]-base[2])<24),rgb=[0,1,2].map(j=>Math.round(mean((near.length?near:px).map(p=>p[j]))));let ink=0;for(const p of px){if(Math.hypot(p[0]-rgb[0],p[1]-rgb[1],p[2]-rgb[2])>34&&Math.abs(lum(p)-lum(rgb))>18)ink++}return{rgb,ink:ink/Math.max(1,px.length),support:bn/Math.max(1,px.length)}}
function buildCells(c,S){const X=c.getContext('2d',{willReadFrequently:true}),W=c.width,H=c.height,d=X.getImageData(0,0,W,H).data,out=[];for(let r=0;r<S.rows;r++)for(let col=0;col<S.cols;col++){const x=col*W/S.cols,y=r*H/S.rows,w=W/S.cols,h=H/S.rows,z=dominant(d,W,H,x,y,w,h),orig=S.cells[r*S.cols+col],occ=!!(orig?.occupied||orig?.code||sat(z.rgb)>.045||lum(z.rgb)<232||z.ink>.018);out.push({r,col,x,y,w,h,...z,orig,occ,cluster:-1,votes:new Map()})}return out}
function makeClusters(cells){const qs=[];for(const s of cells){if(!s.occ)continue;let bi=-1,bd=1e9;for(let i=0;i<qs.length;i++){const d=de(s.rgb,qs[i].rgb);if(d<bd){bd=d;bi=i}}if(bi>=0&&bd<5.2){const q=qs[bi],n=q.cells.length;q.cells.push(s);q.rgb=q.rgb.map((v,j)=>(v*n+s.rgb[j])/(n+1));s.cluster=bi}else{s.cluster=qs.length;qs.push({rgb:[...s.rgb],cells:[s],votes:new Map(),code:'',conf:'low'})}}return qs}
function region(src,x,y,w,h,max=3000){if(w<18||h<18)return null;const sc=Math.min(6,max/Math.max(w,h)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(w*sc));c.height=Math.max(1,Math.round(h*sc));const X=c.getContext('2d',{willReadFrequently:true});X.imageSmoothingEnabled=true;X.imageSmoothingQuality='high';X.drawImage(src,x,y,w,h,0,0,c.width,c.height);return c}
function bgAround(c,b){const ctx=c.getContext('2d',{willReadFrequently:true}),W=c.width,H=c.height,d=ctx.getImageData(0,0,W,H).data,bw=Math.max(8,b.x1-b.x0),bh=Math.max(8,b.y1-b.y0);return dominant(d,W,H,b.x0-bw*.45,b.y0-bh*.45,bw*1.9,bh*1.9).rgb}
function parseLegendText(text){const m=new Map(),s=String(text||'').toUpperCase().replace(/\n/g,' ');const re=/\b((?:ZG|[A-HMPRQTY])\s*\d{1,2})\s*[\(\[]?\s*(\d{1,3})\s*[\)\]]?/g;for(const x of s.matchAll(re)){const k=norm(x[1]);if(!k)continue;const n=parseInt(x[2],10);if(Number.isFinite(n)&&n>0&&n<1000)m.set(k,n)}return m}
async function readLegend(worker,src,r){const canvases=[];const bottom=src.height-(r.y+r.h),right=src.width-(r.x+r.w),top=r.y;if(bottom>25)canvases.push(region(src,0,r.y+r.h,src.width,bottom));if(right>25)canvases.push(region(src,r.x+r.w,0,right,src.height));if(top>25)canvases.push(region(src,0,0,src.width,top));const codes=new Map(),counts=new Map();try{await worker.setParameters({tessedit_pageseg_mode:'6',tessedit_char_whitelist:'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789()'});for(const c of canvases.filter(Boolean)){const z=await worker.recognize(c);for(const[k,n]of parseLegendText(z.data?.text))counts.set(k,n);for(const w of z.data?.words||[]){const k=norm(w.text);if(!k||!w.bbox)continue;if(!codes.has(k))codes.set(k,[]);codes.get(k).push(bgAround(c,w.bbox))}}}catch(_){}const rgb=new Map();for(const[k,a]of codes)rgb.set(k,[0,1,2].map(i=>Math.round(median(a.map(x=>x[i])))));return{codes:new Set([...codes.keys(),...counts.keys()]),counts,rgb}}
function cellTile(c,s,binary=true){const t=document.createElement('canvas');t.width=112;t.height=74;const T=t.getContext('2d',{willReadFrequently:true});T.fillStyle='#fff';T.fillRect(0,0,t.width,t.height);const sx=s.x+s.w*.08,sy=s.y+s.h*.08,sw=s.w*.84,sh=s.h*.84,raw=document.createElement('canvas');raw.width=Math.max(2,Math.round(sw));raw.height=Math.max(2,Math.round(sh));const R=raw.getContext('2d',{willReadFrequently:true});R.drawImage(c,sx,sy,sw,sh,0,0,raw.width,raw.height);if(binary){const im=R.getImageData(0,0,raw.width,raw.height),d=im.data,B=s.rgb,L=lum(B);for(let i=0;i<d.length;i+=4){const p=[d[i],d[i+1],d[i+2]],dist=Math.hypot(p[0]-B[0],p[1]-B[1],p[2]-B[2]),ld=Math.abs(lum(p)-L),ink=dist>29&&ld>12,v=ink?0:255;d[i]=d[i+1]=d[i+2]=v;d[i+3]=255}R.putImageData(im,0,0)}T.imageSmoothingEnabled=false;T.drawImage(raw,6,6,t.width-12,t.height-12);return t}
function buildSheet(c,cells,binary){const use=cells.filter(x=>x.occ),tw=112,th=74,nc=7,nr=Math.ceil(use.length/nc),sh=document.createElement('canvas');sh.width=nc*tw;sh.height=Math.max(th,nr*th);const X=sh.getContext('2d');X.fillStyle='#fff';X.fillRect(0,0,sh.width,sh.height);const map=[];use.forEach((s,i)=>{const col=i%nc,row=Math.floor(i/nc);X.drawImage(cellTile(c,s,binary),col*tw,row*th);map.push(s)});return{sh,map,tw,th,nc}}
async function ocrCells(worker,c,cells){let hits=0;for(const binary of [true,false]){const{sh,map,tw,th,nc}=buildSheet(c,cells,binary);for(const psm of [6,11]){try{await worker.setParameters({tessedit_pageseg_mode:String(psm),tessedit_char_whitelist:'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'});const z=await worker.recognize(sh);for(const w of z.data?.words||[]){const k=norm(w.text);if(!k||!w.bbox)continue;const cx=(w.bbox.x0+w.bbox.x1)/2,cy=(w.bbox.y0+w.bbox.y1)/2,idx=Math.floor(cy/th)*nc+Math.floor(cx/tw),s=map[idx];if(!s)continue;s.votes.set(k,(s.votes.get(k)||0)+1);hits++}}catch(_){}}}return hits}
function aggregateVotes(qs){for(const q of qs){for(const s of q.cells){for(const[k,n]of s.votes)q.votes.set(k,(q.votes.get(k)||0)+n);const old=norm(s.orig?.code);if(old)q.votes.set(old,(q.votes.get(old)||0)+.15)}}}
function ref(k,off=[0,0,0]){const e=MARD.get(k);return[e[1]+off[0],e[2]+off[1],e[3]+off[2]].map(v=>clamp(v,0,255))}
function calibration(legend){const pairs=[];for(const[k,rgb]of legend.rgb){if(!MARD.has(k))continue;pairs.push([rgb,ref(k)])}return pairs.length?[0,1,2].map(i=>clamp(median(pairs.map(p=>p[0][i]-p[1][i])),-55,55)):[0,0,0]}
function voteTop(q,allowed){const a=[...q.votes].filter(([k])=>!allowed||allowed.has(k)).sort((x,y)=>y[1]-x[1]);return a[0]||['',0]}
function score(q,k,legend,off){let s=de(q.rgb,legend.rgb.get(k)||ref(k,off));const target=legend.counts.get(k);if(target){const dif=Math.abs(q.cells.length-target);s+=dif===0?-14:dif===1?-6:Math.min(35,dif*2.8)}const v=q.votes.get(k)||0;s-=Math.min(16,v*2.6);return s}
function assign(qs,legend){const off=calibration(legend),pool=new Set(legend.codes);const repeats=new Map();for(const q of qs)for(const[k,n]of q.votes)repeats.set(k,(repeats.get(k)||0)+n);for(const[k,n]of repeats)if(n>=2)pool.add(k);const strongLegend=legend.codes.size>=3;const candidate=strongLegend?new Set(legend.codes):pool;const pairs=[];for(let qi=0;qi<qs.length;qi++){const q=qs[qi];for(const k of candidate)pairs.push({qi,k,s:score(q,k,legend,off)})}pairs.sort((a,b)=>a.s-b.s);const usedQ=new Set(),usedK=new Set();for(const p of pairs){if(usedQ.has(p.qi)||usedK.has(p.k))continue;const q=qs[p.qi],target=legend.counts.get(p.k),colorD=de(q.rgb,legend.rgb.get(p.k)||ref(p.k,off));const countOK=!target||Math.abs(q.cells.length-target)<=Math.max(2,Math.ceil(target*.08));if((countOK&&colorD<24)||p.s<8){q.code=p.k;q.conf=target&&q.cells.length===target?'very-high':'high';usedQ.add(p.qi);usedK.add(p.k)}}
// Unassigned clusters: first use overwhelming OCR, then nearest already-known/legend color.
for(const q of qs){if(q.code)continue;const[v,vn]=voteTop(q,strongLegend?legend.codes:null);if(v&&vn>=3){q.code=v;q.conf='medium';continue}let best='',bd=1e9;for(const k of candidate){const d=de(q.rgb,legend.rgb.get(k)||ref(k,off));if(d<bd){bd=d;best=k}}if(best&&bd<13){q.code=best;q.conf='medium'}}
// If one true color split into multiple nearly-identical clusters, force same code.
for(const q of qs){if(q.code)continue;let best=null,bd=1e9;for(const p of qs){if(!p.code)continue;const d=de(q.rgb,p.rgb);if(d<bd){bd=d;best=p}}if(best&&bd<6){q.code=best.code;q.conf='merged'}}
return{pool,candidate,off}}
function apply(qs){let changed=0,assigned=0;for(const q of qs){if(!q.code)continue;assigned++;for(const s of q.cells){if(s.orig.code!==q.code)changed++;s.orig.code=q.code;s.orig.rgb=[...s.rgb];s.orig.hex=hex(s.rgb);s.orig.occupied=true;s.orig.v9Confidence=q.conf}}return{changed,assigned}}
async function run(){const S=window.__pindouV6,src=$('sourceCanvas'),r=rect();if(!S?.active||!S.worker||!r)return;notice('V9 正在做最终一致性校验：先读图纸色卡数量，再逐格 OCR，最后把“同一种底色”强制统一…');const c=crop(src,r),cells=buildCells(c,S),qs=makeClusters(cells),legend=await readLegend(S.worker,src,r);const hits=await ocrCells(S.worker,c,cells);aggregateVotes(qs);assign(qs,legend);const info=apply(qs);$('showAllBtn')?.click();const recognized=qs.filter(q=>q.code).length,un=qs.length-recognized;const countInfo=legend.counts.size?`，其中 ${legend.counts.size} 种读到了图纸标注颗数`:'；图纸颗数未完整读到';notice(`V9 完成：图纸色卡识别 ${legend.codes.size} 种${countInfo}；逐格 OCR 命中 ${hits} 次；实际底色 ${qs.length} 组，统一/修正 ${info.changed} 格；仍有 ${un} 个底色组低置信。现在同一种底色只会保留一个色号。`,un<=1?'ok':'warn')}
let timer=null;const box=$('detectNotice');if(box){new MutationObserver(()=>{const t=box.textContent||'';if(!t.startsWith('V8 完成'))return;clearTimeout(timer);timer=setTimeout(()=>run().catch(e=>notice(`V9 校验失败：${e.message||e}`,'warn')),120)}).observe(box,{childList:true,characterData:true,subtree:true})}
})();
