(() => {
'use strict';
const $=id=>document.getElementById(id), COLORS=window.PINDOU_MARD_COLORS||[], MARD=new Set(COLORS.map(x=>x[0]));
if(!COLORS.length)return;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), mean=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0;
const lum=x=>.2126*x[0]+.7152*x[1]+.0722*x[2], hex=x=>'#'+x.map(v=>clamp(Math.round(v),0,255).toString(16).padStart(2,'0')).join('');
function code(raw){let s=String(raw||'').toUpperCase().replace(/[^A-Z0-9]/g,'');if(MARD.has(s))return s;const m=s.match(/^([A-Z]{1,2})([0-9OILSZGB]{1,3})$/);if(!m)return'';s=m[1]+m[2].replace(/O/g,'0').replace(/[IL]/g,'1').replace(/Z/g,'2').replace(/S/g,'5').replace(/G/g,'6').replace(/B/g,'8');return MARD.has(s)?s:''}
function srgb(v){v/=255;return v<=.04045?v/12.92:Math.pow((v+.055)/1.055,2.4)}
function lab(a){const r=srgb(a[0]),g=srgb(a[1]),b=srgb(a[2]),x=(.4124*r+.3576*g+.1805*b)/.95047,y=.2126*r+.7152*g+.0722*b,z=(.0193*r+.1192*g+.9505*b)/1.08883,f=t=>t>.008856?Math.cbrt(t):7.787*t+16/116,fx=f(x),fy=f(y),fz=f(z);return[116*fy-16,500*(fx-fy),200*(fy-fz)]}
function de(a,b){const A=lab(a),B=lab(b);return Math.hypot(A[0]-B[0],A[1]-B[1],A[2]-B[2])}
function rect(){const c=$('sourceCanvas'),o=$('cropOverlay');if(!c?.width)return null;let x=parseFloat(o.style.left),y=parseFloat(o.style.top),w=parseFloat(o.style.width),h=parseFloat(o.style.height);if(!Number.isFinite(x)||w<2){x=0;y=0;w=c.width;h=c.height}return{x:clamp(x,0,c.width-1),y:clamp(y,0,c.height-1),w:clamp(w,1,c.width-x),h:clamp(h,1,c.height-y)}}
function crop(src,r){const c=document.createElement('canvas');c.width=Math.round(r.w);c.height=Math.round(r.h);c.getContext('2d',{willReadFrequently:true}).drawImage(src,r.x,r.y,r.w,r.h,0,0,c.width,c.height);return c}
function dom(data,W,H,x,y,w,h){const bins=new Map(),px=[],step=Math.max(1,Math.floor(Math.min(w,h)/16));for(let yy=Math.max(0,Math.floor(y));yy<Math.min(H,y+h);yy+=step)for(let xx=Math.max(0,Math.floor(x));xx<Math.min(W,x+w);xx+=step){const i=(yy*W+xx)*4,p=[data[i],data[i+1],data[i+2]],k=`${Math.round(p[0]/8)*8},${Math.round(p[1]/8)*8},${Math.round(p[2]/8)*8}`;px.push(p);bins.set(k,(bins.get(k)||0)+1)}let k='255,255,255',bn=-1;for(const[a,n]of bins)if(n>bn){bn=n;k=a}const b=k.split(',').map(Number),q=px.filter(p=>Math.hypot(p[0]-b[0],p[1]-b[1],p[2]-b[2])<26);return[0,1,2].map(j=>Math.round(mean((q.length?q:px).map(p=>p[j]))))}
function samples(c,rows,cols,S){const ctx=c.getContext('2d',{willReadFrequently:true}),W=c.width,H=c.height,d=ctx.getImageData(0,0,W,H).data,out=[];for(let r=0;r<rows;r++)for(let col=0;col<cols;col++){const x=col*W/cols,y=r*H/rows,w=W/cols,h=H/rows,rgb=dom(d,W,H,x+w*.2,y+h*.2,w*.6,h*.6),orig=S.cells[r*cols+col];out.push({r,col,x,y,w,h,rgb,orig,occ:!!(orig?.occupied||orig?.code),cluster:-1})}return out}
function clusters(ss){const qs=[];for(const s of ss){if(!s.occ)continue;let bi=-1,bd=1e9;for(let i=0;i<qs.length;i++){const d=de(s.rgb,qs[i].rgb);if(d<bd){bd=d;bi=i}}if(bi>=0&&bd<3.1){const q=qs[bi],n=q.a.length;q.a.push(s);q.rgb=q.rgb.map((v,i)=>(v*n+s.rgb[i])/(n+1));s.cluster=bi}else{s.cluster=qs.length;qs.push({rgb:[...s.rgb],a:[s],votes:new Map()})}}return qs}
function region(src,x,y,w,h){if(w<20||h<20)return null;const sc=Math.min(4,2200/Math.max(w,h)),c=document.createElement('canvas');c.width=Math.round(w*sc);c.height=Math.round(h*sc);c.getContext('2d',{willReadFrequently:true}).drawImage(src,x,y,w,h,0,0,c.width,c.height);return c}
function bgAt(c,b){const ctx=c.getContext('2d',{willReadFrequently:true}),W=c.width,H=c.height,d=ctx.getImageData(0,0,W,H).data,bw=Math.max(4,b.x1-b.x0),bh=Math.max(4,b.y1-b.y0);return dom(d,W,H,b.x0-bw*.55,b.y0-bh*.65,bw*2.1,bh*2.3)}
async function legend(worker,src,r){const regs=[];if(src.height-r.y-r.h>24)regs.push(region(src,0,r.y+r.h,src.width,src.height-r.y-r.h));if(src.width-r.x-r.w>24)regs.push(region(src,r.x+r.w,0,src.width-r.x-r.w,src.height));if(r.y>24)regs.push(region(src,0,0,src.width,r.y));const m=new Map();try{await worker.setParameters({tessedit_pageseg_mode:'6',tessedit_char_whitelist:'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'});for(const c of regs.filter(Boolean)){const z=await worker.recognize(c);for(const w of z.data?.words||[]){const k=code(w.text);if(!k||!w.bbox)continue;if(!m.has(k))m.set(k,[]);m.get(k).push(bgAt(c,w.bbox))}}}catch(_){}const out=new Map();for(const[k,a]of m)out.set(k,[0,1,2].map(i=>Math.round(mean(a.map(x=>x[i])))));return out}
function sheet(c,qs){const picks=[];qs.forEach(q=>[...q.a].sort((a,b)=>(b.orig?.direct?1:0)-(a.orig?.direct?1:0)).slice(0,3).forEach(s=>picks.push({q,s})));const tw=126,th=84,nc=5,sh=document.createElement('canvas');sh.width=nc*tw;sh.height=Math.max(th,Math.ceil(picks.length/nc)*th);const X=sh.getContext('2d',{willReadFrequently:true});X.fillStyle='#fff';X.fillRect(0,0,sh.width,sh.height);const map=[];picks.forEach((p,i)=>{const ox=i%nc*tw,oy=Math.floor(i/nc)*th,t=document.createElement('canvas');t.width=tw;t.height=th;const T=t.getContext('2d',{willReadFrequently:true});T.fillStyle='#fff';T.fillRect(0,0,tw,th);T.drawImage(c,p.s.x+p.s.w*.1,p.s.y+p.s.h*.1,p.s.w*.8,p.s.h*.8,5,5,tw-10,th-10);const im=T.getImageData(0,0,tw,th),d=im.data,B=p.s.rgb,L=lum(B);for(let k=0;k<d.length;k+=4){const q=[d[k],d[k+1],d[k+2]],ink=Math.hypot(q[0]-B[0],q[1]-B[1],q[2]-B[2])>42&&Math.abs(lum(q)-L)>18,v=ink?0:255;d[k]=d[k+1]=d[k+2]=v}T.putImageData(im,0,0);X.drawImage(t,ox,oy);map.push(p.q)});return{sh,map,tw,th,nc}}
async function votes(worker,c,qs){for(const q of qs)for(const s of q.a)if(s.orig?.direct&&code(s.orig.code))q.votes.set(s.orig.code,(q.votes.get(s.orig.code)||0)+1);const{sh,map,tw,th,nc}=sheet(c,qs);let hits=0;try{await worker.setParameters({tessedit_pageseg_mode:'6',tessedit_char_whitelist:'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'});const z=await worker.recognize(sh);for(const w of z.data?.words||[]){const k=code(w.text);if(!k||!w.bbox)continue;const i=Math.floor(((w.bbox.y0+w.bbox.y1)/2)/th)*nc+Math.floor(((w.bbox.x0+w.bbox.x1)/2)/tw),q=map[i];if(q){q.votes.set(k,(q.votes.get(k)||0)+4);hits++}}}catch(_){}return hits}
function nearest(rgb,m){let k='',d=1e9,s=1e9;for(const[a,b]of m){const x=de(rgb,b);if(x<d){s=d;d=x;k=a}else if(x<s)s=x}return{k,d,gap:s-d}}
function decide(qs,lm){let changed=0,uncertain=0;for(const q of qs){const vv=[...q.votes].sort((a,b)=>b[1]-a[1]),v=vv[0]||['',0],v2=vv[1]||['',0],n=nearest(q.rgb,lm),counts=new Map();for(const s of q.a){const k=code(s.orig?.code);if(k)counts.set(k,(counts.get(k)||0)+1)}let k=[...counts].sort((a,b)=>b[1]-a[1])[0]?.[0]||'',conf='low';if(n.k&&n.d<6.5&&(n.gap>1||v[0]===n.k)){k=n.k;conf='high'}else if(v[0]&&v[1]>=8&&v[1]-v2[1]>=3){k=v[0];conf='high'}else if(n.k&&n.d<10.5&&n.gap>.65){k=n.k;conf='medium'}else if(v[0]&&v[1]>=4&&v[1]-v2[1]>=2){k=v[0];conf='medium'}else if(k&&lm.has(k)&&n.k&&n.d+2<de(q.rgb,lm.get(k))&&n.d<13){k=n.k;conf='medium'}if(conf==='low')uncertain++;if(!k)continue;for(const s of q.a){if(s.orig.code!==k)changed++;s.orig.code=k;s.orig.rgb=[...s.rgb];s.orig.hex=hex(s.rgb);s.orig.v7Confidence=conf}}return{changed,uncertain}}
function notice(t,k='ok'){const e=$('detectNotice');if(e){e.textContent=t;e.className=`notice ${k}`;e.classList.remove('hidden')}}
let serial=0;async function refine(id){const S=window.__pindouV6,src=$('sourceCanvas'),r=rect();if(!S?.active||!S.worker||!r)return;const c=crop(src,r),ss=samples(c,S.rows,S.cols,S),qs=clusters(ss);notice('V7 正在二次精校：重新读取每格中心，并用图纸色卡 + 多格 OCR 复核…');const lm=await legend(S.worker,src,r);if(id!==serial)return;const hits=await votes(S.worker,c,qs);if(id!==serial)return;const info=decide(qs,lm);$('showAllBtn')?.click();notice(`V7 精校完成：色卡 ${lm.size} 种；每种底色最多抽 3 格放大 OCR，命中 ${hits} 次；修正 ${info.changed} 格；仍有 ${info.uncertain} 个低置信颜色组。`,info.uncertain<3?'ok':'warn')}
window.addEventListener('click',e=>{const b=e.target?.closest?.('#recognizeBtn');if(!b)return;const id=++serial;let busy=false,n=0;const tm=setInterval(()=>{n++;if(b.disabled)busy=true;const S=window.__pindouV6;if((busy&&!b.disabled&&S?.active)||n>480){clearInterval(tm);if(busy&&S?.active)refine(id).catch(x=>notice(`V7 精校失败：${x.message||x}`,'warn'))}},250)},true);

// Crop box: drag whole box, drag 8 handles, plus 1px fine-tune buttons.
const st=document.createElement('style');st.textContent=`.crop-overlay.v7e{pointer-events:auto!important;touch-action:none;cursor:move}.v7h{position:absolute;width:24px;height:24px;margin:-12px;border-radius:50%;background:#fff;border:3px solid #ff6f4d;box-shadow:0 2px 7px #0003;z-index:9;touch-action:none}.v7nw{left:0;top:0}.v7n{left:50%;top:0}.v7ne{left:100%;top:0}.v7e2{left:100%;top:50%}.v7se{left:100%;top:100%}.v7s{left:50%;top:100%}.v7sw{left:0;top:100%}.v7w{left:0;top:50%}.v7tools{display:none;grid-template-columns:repeat(8,1fr);gap:5px;margin-top:7px}.v7tools.show{display:grid}.v7tools button{min-height:34px;padding:3px;border-radius:9px;font-size:11px;background:#fff7f1;border:1px solid #ead9cc}@media(max-width:430px){.v7tools{grid-template-columns:repeat(4,1fr)}}`;document.head.appendChild(st);
const o=$('cropOverlay'),vp=$('sourceViewport'),cv=$('sourceCanvas');let drag=null,last=null,tools=null;
function rs(){return{x:parseFloat(o.style.left)||0,y:parseFloat(o.style.top)||0,w:parseFloat(o.style.width)||1,h:parseFloat(o.style.height)||1}}
function pt(e){const r=cv.getBoundingClientRect();return{x:(e.clientX-r.left)*cv.width/r.width,y:(e.clientY-r.top)*cv.height/r.height}}
function cropMode(){return vp?.classList.contains('mode-crop')}
function refresh(){if(!o)return;const r=rs(),full=Math.abs(r.x)<2&&Math.abs(r.y)<2&&Math.abs(r.w-cv.width)<3&&Math.abs(r.h-cv.height)<3;o.classList.toggle('v7e',cropMode()&&!full);tools?.classList.toggle('show',cropMode());const s=o.querySelector('span');if(s)s.textContent=cropMode()?'拖动移动 · 拉圆点缩放':'识别区域'}
function setr(r,remember=true){const W=cv.width,H=cv.height,m=8;r={x:clamp(r.x,0,W-m),y:clamp(r.y,0,H-m),w:Math.max(m,r.w),h:Math.max(m,r.h)};r.w=Math.min(r.w,W-r.x);r.h=Math.min(r.h,H-r.y);o.style.left=r.x+'px';o.style.top=r.y+'px';o.style.width=r.w+'px';o.style.height=r.h+'px';if(remember)last={...r};const ci=$('cropInfo');if(ci)ci.textContent=`${Math.round(r.w)} × ${Math.round(r.h)} px`;[['leftCrop','leftVal',r.x/W*100],['rightCrop','rightVal',(r.x+r.w)/W*100],['topCrop','topVal',r.y/H*100],['bottomCrop','bottomVal',(r.y+r.h)/H*100]].forEach(([a,b,v])=>{if($(a))$(a).value=v;if($(b))$(b).textContent=v.toFixed(1)+'%'});refresh()}
if(o&&vp&&cv){[['nw','v7nw'],['n','v7n'],['ne','v7ne'],['e','v7e2'],['se','v7se'],['s','v7s'],['sw','v7sw'],['w','v7w']].forEach(([d,c])=>{const h=document.createElement('i');h.className=`v7h ${c}`;h.dataset.d=d;o.appendChild(h)});o.addEventListener('pointerdown',e=>{if(!cropMode())return;e.preventDefault();e.stopPropagation();drag={id:e.pointerId,d:e.target.dataset.d||'move',r:rs(),p:pt(e)};o.setPointerCapture?.(e.pointerId)});o.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;e.preventDefault();e.stopPropagation();const p=pt(e),dx=p.x-drag.p.x,dy=p.y-drag.p.y,s=drag.r,r={...s},d=drag.d;if(d==='move'){r.x+=dx;r.y+=dy}else{if(d.includes('w')){r.x+=dx;r.w-=dx}if(d.includes('e'))r.w+=dx;if(d.includes('n')){r.y+=dy;r.h-=dy}if(d.includes('s'))r.h+=dy}setr(r)});const end=e=>{if(drag?.id===e.pointerId){e.preventDefault();e.stopPropagation();drag=null}};o.addEventListener('pointerup',end);o.addEventListener('pointercancel',end);vp.addEventListener('pointerdown',e=>{if(cropMode()&&!o.contains(e.target))last=null},true);vp.addEventListener('pointerup',()=>setTimeout(()=>{if(cropMode()&&!last)setr(rs())},0),true);tools=document.createElement('div');tools.className='v7tools';tools.innerHTML='<button data-x="l">←1px</button><button data-x="r">→1px</button><button data-x="u">↑1px</button><button data-x="d">↓1px</button><button data-x="wn">宽−</button><button data-x="wp">宽＋</button><button data-x="hn">高−</button><button data-x="hp">高＋</button>';vp.insertAdjacentElement('afterend',tools);tools.addEventListener('click',e=>{const x=e.target.dataset.x;if(!x)return;const r=rs();if(x==='l')r.x--;if(x==='r')r.x++;if(x==='u')r.y--;if(x==='d')r.y++;if(x==='wn'){r.x+=.5;r.w--}if(x==='wp'){r.x-=.5;r.w++}if(x==='hn'){r.y+=.5;r.h--}if(x==='hp'){r.y-=.5;r.h++}setr(r)});new MutationObserver(refresh).observe(vp,{attributes:true,attributeFilter:['class']});$('clearCellBtn')?.addEventListener('click',()=>{const k=last?{...last}:null;if(k)setTimeout(()=>setr(k),0)},true);$('clearCropBtn')?.addEventListener('click',()=>{last=null;setTimeout(()=>refresh(),0)},true);$('rotateLeftBtn')?.addEventListener('click',()=>last=null,true);$('rotateRightBtn')?.addEventListener('click',()=>last=null,true);refresh()}
const rb=$('recognizeBtn');if(rb)rb.textContent='识别 + 二次精校（V7）';
})();
